export const currencies = [
  { code: 'AED', label: 'UAE dirham' },
  { code: 'AFN', label: 'Afghan afghani' },
  { code: 'ALL', label: 'Albanian lek' },
  { code: 'AMD', label: 'Armenian dram' },
  { code: 'ANG', label: 'Netherlands Antillean gulden' },
  { code: 'AOA', label: 'Angolan kwanza' },
  { code: 'ARS', label: 'Argentine peso' },
  { code: 'AUD', label: 'Australian dollar' },
  { code: 'AWG', label: 'Aruban florin' },
  { code: 'AZN', label: 'Azerbaijani manat' },
  //   { code: 'BAM', label: 'Bosnia and Herzegovina konvertibilna marka' },
  { code: 'BBD', label: 'Barbadian dollar' },
  { code: 'BDT', label: 'Bangladeshi taka' },
  { code: 'BGN', label: 'Bulgarian lev' },
  { code: 'BHD', label: 'Bahraini dinar' },
  { code: 'BIF', label: 'Burundi franc' },
  { code: 'BMD', label: 'Bermudian dollar' },
  { code: 'BND', label: 'Brunei dollar' },
  { code: 'BOB', label: 'Bolivian boliviano' },
  { code: 'BRL', label: 'Brazilian real' },
  { code: 'BSD', label: 'Bahamian dollar' },
  { code: 'BTN', label: 'Bhutanese ngultrum' },
  { code: 'BWP', label: 'Botswana pula' },
  //   { code: 'BYR', label: 'Belarusian ruble' },
  { code: 'BZD', label: 'Belize dollar' },
  { code: 'CAD', label: 'Canadian dollar' },
  { code: 'CDF', label: 'Congolese franc' },
  { code: 'CHF', label: 'Swiss franc' },
  { code: 'CLP', label: 'Chilean peso' },
  { code: 'CNY', label: 'Chinese/Yuan renminbi' },
  { code: 'COP', label: 'Colombian peso' },
  { code: 'CRC', label: 'Costa Rican colon' },
  //   { code: 'CUC', label: 'Cuban peso' },
  { code: 'CVE', label: 'Cape Verdean escudo' },
  { code: 'CZK', label: 'Czech koruna' },
  { code: 'DJF', label: 'Djiboutian franc' },
  { code: 'DKK', label: 'Danish krone' },
  { code: 'DOP', label: 'Dominican peso' },
  { code: 'DZD', label: 'Algerian dinar' },
  //   { code: 'EEK', label: 'Estonian kroon' },
  { code: 'EGP', label: 'Egyptian pound' },
  { code: 'ERN', label: 'Eritrean nakfa' },
  { code: 'ETB', label: 'Ethiopian birr' },
  { code: 'EUR', label: 'European Euro' },
  { code: 'FJD', label: 'Fijian dollar' },
  { code: 'FKP', label: 'Falkland Islands pound' },
  { code: 'GBP', label: 'British pound' },
  { code: 'GEL', label: 'Georgian lari' },
  { code: 'GHS', label: 'Ghanaian cedi' },
  { code: 'GIP', label: 'Gibraltar pound' },
  { code: 'GMD', label: 'Gambian dalasi' },
  { code: 'GNF', label: 'Guinean franc' },
  //   { code: 'GQE', label: 'Central African CFA franc' },
  { code: 'GTQ', label: 'Guatemalan quetzal' },
  { code: 'GYD', label: 'Guyanese dollar' },
  { code: 'HKD', label: 'Hong Kong dollar' },
  { code: 'HNL', label: 'Honduran lempira' },
  { code: 'HRK', label: 'Croatian kuna' },
  { code: 'HTG', label: 'Haitian gourde' },
  { code: 'HUF', label: 'Hungarian forint' },
  { code: 'IDR', label: 'Indonesian rupiah' },
  { code: 'ILS', label: 'Israeli new sheqel' },
  { code: 'INR', label: 'Indian rupee' },
  { code: 'IQD', label: 'Iraqi dinar' },
  { code: 'IRR', label: 'Iranian rial' },
  { code: 'ISK', label: 'Icelandic kr\u00f3na' },
  { code: 'JMD', label: 'Jamaican dollar' },
  { code: 'JOD', label: 'Jordanian dinar' },
  { code: 'JPY', label: 'Japanese yen' },
  { code: 'KES', label: 'Kenyan shilling' },
  { code: 'KGS', label: 'Kyrgyzstani som' },
  { code: 'KHR', label: 'Cambodian riel' },
  { code: 'KMF', label: 'Comorian franc' },
  { code: 'KPW', label: 'North Korean won' },
  { code: 'KRW', label: 'South Korean won' },
  { code: 'KWD', label: 'Kuwaiti dinar' },
  { code: 'KYD', label: 'Cayman Islands dollar' },
  { code: 'KZT', label: 'Kazakhstani tenge' },
  { code: 'LAK', label: 'Lao kip' },
  { code: 'LBP', label: 'Lebanese lira' },
  { code: 'LKR', label: 'Sri Lankan rupee' },
  { code: 'LRD', label: 'Liberian dollar' },
  //   { code: 'LSL', label: 'Lesotho loti' },
  { code: 'LTL', label: 'Lithuanian litas' },
  //   { code: 'LVL', label: 'Latvian lats' },
  { code: 'LYD', label: 'Libyan dinar' },
  { code: 'MAD', label: 'Moroccan dirham' },
  { code: 'MDL', label: 'Moldovan leu' },
  { code: 'MGA', label: 'Malagasy ariary' },
  { code: 'MKD', label: 'Macedonian denar' },
  { code: 'MMK', label: 'Myanma kyat' },
  { code: 'MNT', label: 'Mongolian tugrik' },
  { code: 'MOP', label: 'Macanese pataca' },
  { code: 'MRO', label: 'Mauritanian ouguiya' },
  { code: 'MUR', label: 'Mauritian rupee' },
  { code: 'MVR', label: 'Maldivian rufiyaa' },
  { code: 'MWK', label: 'Malawian kwacha' },
  { code: 'MXN', label: 'Mexican peso' },
  { code: 'MYR', label: 'Malaysian ringgit' },
  //   { code: 'MZM', label: 'Mozambican metical' },
  { code: 'NAD', label: 'Namibian dollar' },
  { code: 'NGN', label: 'Nigerian naira' },
  { code: 'NIO', label: 'Nicaraguan c\u00f3rdoba' },
  { code: 'NOK', label: 'Norwegian krone' },
  { code: 'NPR', label: 'Nepalese rupee' },
  { code: 'NZD', label: 'New Zealand dollar' },
  { code: 'OMR', label: 'Omani rial' },
  //   { code: 'PAB', label: 'Panamanian balboa' },
  { code: 'PEN', label: 'Peruvian nuevo sol' },
  { code: 'PGK', label: 'Papua New Guinean kina' },
  { code: 'PHP', label: 'Philippine peso' },
  { code: 'PKR', label: 'Pakistani rupee' },
  { code: 'PLN', label: 'Polish zloty' },
  { code: 'PYG', label: 'Paraguayan guarani' },
  { code: 'QAR', label: 'Qatari riyal' },
  { code: 'RON', label: 'Romanian leu' },
  { code: 'RSD', label: 'Serbian dinar' },
  { code: 'RUB', label: 'Russian ruble' },
  { code: 'SAR', label: 'Saudi riyal' },
  { code: 'SCR', label: 'Seychellois rupee' },
  { code: 'SBD', label: 'Solomon Islands dollar' },
  //   { code: 'SDG', label: 'Sudanese pound' },
  { code: 'SEK', label: 'Swedish krona' },
  { code: 'SGD', label: 'Singapore dollar' },
  { code: 'SHP', label: 'Saint Helena pound' },
  { code: 'SLL', label: 'Sierra Leonean leone' },
  { code: 'SOS', label: 'Somali shilling' },
  { code: 'SRD', label: 'Surinamese dollar' },
  { code: 'SYP', label: 'Syrian pound' },
  { code: 'SZL', label: 'Swazi lilangeni' },
  { code: 'THB', label: 'Thai baht' },
  { code: 'TJS', label: 'Tajikistani somoni' },
  //   { code: 'TMT', label: 'Turkmen manat' },
  { code: 'TND', label: 'Tunisian dinar' },
  { code: 'TRY', label: 'Turkish new lira' },
  { code: 'TTD', label: 'Trinidad and Tobago dollar' },
  { code: 'TWD', label: 'New Taiwan dollar' },
  { code: 'TZS', label: 'Tanzanian shilling' },
  { code: 'UAH', label: 'Ukrainian hryvnia' },
  { code: 'UGX', label: 'Ugandan shilling' },
  { code: 'USD', label: 'United States dollar' },
  { code: 'UYU', label: 'Uruguayan peso' },
  { code: 'UZS', label: 'Uzbekistani som' },
  //   { code: 'VEB', label: 'Venezuelan bolivar' },
  { code: 'VND', label: 'Vietnamese dong' },
  { code: 'VUV', label: 'Vanuatu vatu' },
  { code: 'WST', label: 'Samoan tala' },
  //   { code: 'XAF', label: 'Central African CFA franc' },
  { code: 'XCD', label: 'East Caribbean dollar' },
  //   { code: 'XDR', label: 'Special Drawing Rights' },
  { code: 'XOF', label: 'West African CFA franc' },
  { code: 'XPF', label: 'CFP franc' },
  { code: 'YER', label: 'Yemeni rial' },
  { code: 'ZAR', label: 'South African rand' },
  //   { code: 'ZMK', label: 'Zambian kwacha' },
  //   { code: 'ZWR', label: 'Zimbabwean dollar' },
];
